[atoms.CH3_alkane]
name = "CH3_alkane"
mass = 15.035
epsilon = 0.2709
sigma = 3.6034
n = 14.0
m = 6
cut = 14.0
charge = 0.0
vdw_style = "mie/cut"
coulomb_style = ""

[atoms.CH2_alkane]
name = "CH2_alkane"
mass = 14.027
epsilon = 0.1051
sigma = 4.04
n = 14.0
m = 6
cut = 14.0
charge = 0.0
vdw_style = "mie/cut"
coulomb_style = ""

[bonds."[CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane",]
type = 1
p = [ 200.0, 1.74 ]
style = "harmonic"

[bonds."[CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane",]
type = 1
p = [ 200.0, 1.54 ]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH3_alkane",]
type = 2
p = [ 62.1001, 114.0 ]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane",]
type = 2
p = [ 62.1001, 114.0 ]
style = "harmonic"

[torsions."[CH3_alkane][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane", "CH3_alkane",]
type = 1
p = [ 1.411, -0.271, 3.145, 0.0]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH2_alkane",]
type = 1
p = [ 1.411, -0.271, 3.145, 0.0]
style = "opls"

[torsions."[CH2_alkane][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH3_alkane",]
type = 1
p = [ 1.411, -0.271, 3.145, 0.0]
style = "opls"