# Define force field format (no capitals)
format = "lammps"

# Define if united atoms should be used (True for yes)
UA_flag = true

# Define topology matching priority
# (if two topologies are matched to same atom,
# take entry higher in the list)
topology_priority = [
    "CH3_alkane",
    "CH2_alkene",
    "CH2_alkane"
]


[atoms.CH3_alkane]
name = "CH3_alkane"
mass = 15.035
epsilon = 0.2709
sigma = 3.6034
n = 14.0
m = 6
cut = 14.0
charge = 0.0
atom_no = 6
vdw_style = "mie/cut"
coulomb_style = ""
# Define topology to identify force field type via SMARTS
topology = "[CH3]"

[atoms.CH2_alkane]
name = "CH2_alkane"
mass = 14.027
epsilon = 0.1051
sigma = 4.04
n = 14.0
m = 6
cut = 14.0
charge = 0.0
atom_no = 6
vdw_style = "mie/cut"
coulomb_style = ""
topology = "[CH2]"

[atoms.CH2_alkene]
name = "CH2_alkene"
mass = 14.027
epsilon = 0.199
sigma = 3.6005
n = 14.0
m = 6
cut = 14.0
charge = 0.0
atom_no = 6
vdw_style = "mie/cut"
coulomb_style = ""
topology = "[CH2]=[C]"

[bonds."[CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane",]
p = [ 200.0, 1.74 ]
style = "harmonic"

[bonds."[CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane",]
p = [ 200.0, 1.54 ]
style = "harmonic"

[bonds."[CH2_alkene][CH2_alkene]"]
list = [ "CH2_alkene", "CH2_alkene",]
p = [ 200.0, 1.33 ]
style = "harmonic"

[angles."[CH3_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH3_alkane",]
p = [ 62.1001, 114.0 ]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH3_alkane",]
p = [ 62.1001, 114.0 ]
style = "harmonic"

[angles."[CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane",]
p = [ 62.1001, 114.0 ]
style = "harmonic"

[dihedrals."[CH3_alkane][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH3_alkane", "CH2_alkane", "CH2_alkane", "CH3_alkane",]
p = [ 1.411, -0.271, 3.145, 0.0]
style = "opls"

[dihedrals."[CH2_alkane][CH2_alkane][CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH2_alkane",]
p = [ 1.411, -0.271, 3.145, 0.0]
style = "opls"

[dihedrals."[CH2_alkane][CH2_alkane][CH2_alkane][CH3_alkane]"]
list = [ "CH2_alkane", "CH2_alkane", "CH2_alkane", "CH3_alkane",]
p = [ 1.411, -0.271, 3.145, 0.0]
style = "opls"